apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-loadbalancer

resources:
  - namespace.yaml
  - worker-a-deployment.yaml
  - worker-a-service.yaml
  - worker-b-deployment.yaml
  - worker-b-service.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml

