apiVersion: v1
kind: Service
metadata:
  name: worker-a
  labels:
    app: worker
    instance: worker-a
spec:
  selector:
    app: worker
    instance: worker-a
  ports:
    - name: http
      port: 8000
      targetPort: http

