apiVersion: v1
kind: Service
metadata:
  name: worker-b
  labels:
    app: worker
    instance: worker-b
spec:
  selector:
    app: worker
    instance: worker-b
  ports:
    - name: http
      port: 8000
      targetPort: http